# Generated by Django 4.0.2 on 2022-03-10 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 23, 50, 37, 753476), verbose_name='date published'),
        ),
    ]
