# Generated by Django 4.0.2 on 2022-03-10 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_project_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_series',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 1, 15, 20, 666272), verbose_name='date published'),
        ),
    ]
